name: Unit test

on:
  push:
    branches: ["master"]

  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: cmake
        run: cmake -B build

      - name: make
        run: make test

      - name: test
        run: ./build/bin/test
